import { ImageSourcePropType } from "react-native";

export type Cat = {
  title: string;
  img: ImageSourcePropType;
};
export const cats: Cat[] = [
  { title: "Fruits", img: require("@/assets/images/appel.png") },
  { title: "Vegetables", img: require("@/assets/images/carrot.png")},
  { title: "Dairy", img: require("@/assets/images/beverages.png")},
  { title: "Bakery", img: require("@/assets/images/bakery.png") },
  { title: "Beverages", img: require("@/assets/images/soda.png") },
  { title: "Snacks", img: require("@/assets/images/snakes.png") },
  { title: "Laundry", img: require("@/assets/images/laundry.png") },
];
export type Product = {
  id: string;
  title: string;
  imageUrl: string;
  price: number;
  discountPrice?: number | null;
  discountPercentage?: string | null;
  size: string;
  description: string;
  rating: number;
  category: string;
  stock?: number;
};
export const freeDelivery= 20
export const data: Product[] = [
  {
    id: "1",
    title: "Fresh Carrots",
    imageUrl: "https://freepngimg.com/thumb/carrot/1-carrot-png-image-thumb.png",
    price: 1.0,
    discountPrice: 0.9,
    discountPercentage: "10%",
    description: "Fresh carrots, rich in vitamin A. Price per kg.",
    rating: 4.6,
    category: "Vegetables",
    stock: 100,
    size: "1kg",
  },
  {
    id: "2",
    title: "Organic Broccoli",
    imageUrl: "https://freepngimg.com/thumb/broccoli/12-broccoli-png-image-with-transparent-background-thumb.png",
    price: 2.5,
    discountPrice: 2.0,
    discountPercentage: "20%",
    description: "Fresh broccoli, packed with vitamins. Price per kg.",
    rating: 4.7,
    category: "Vegetables",
    stock: 90,
    size: "1kg",
  },
  {
    id: "3",
    title: "Organic Potatoes",
    imageUrl: "https://freepngimg.com/thumb/potato/7-potato-png-images-pictures-download-thumb.png",
    price: 0.8,
    discountPrice: 0.7,
    discountPercentage: "12%",
    description: "Organic potatoes, great for cooking. Price per kg.",
    rating: 4.4,
    category: "Vegetables",
    stock: 150,
    size: "1kg",
  },
  {
    id: "4",
    title: "Fresh Salad Mix",
    imageUrl: "https://freepngimg.com/thumb/salad/10-salad-png-image-thumb.png",
    price: 2.0,
    discountPrice: 1.8,
    discountPercentage: "10%",
    description: "Fresh salad mix, high in iron. Price per kg.",
    rating: 4.5,
    category: "Vegetables",
    stock: 80,
    size: "1kg",
  },
  {
    id: "5",
    title: "Juicy Tomatoes",
    imageUrl: "https://freepngimg.com/thumb/tomato/6-tomato-png-image-thumb.png",
    price: 1.2,
    discountPrice: 1.0,
    discountPercentage: "16%",
    description: "Juicy tomatoes, perfect for salads. Price per kg.",
    rating: 4.8,
    category: "Vegetables",
    stock: 120,
    size: "1kg",
  },
  {
    id: "6",
    title: "Beetroot Red Bunch",
    imageUrl: "https://freepngimg.com/thumb/beetroot/138457-beetroot-red-bunch-free-hq-image-thumb.png",
    price: 1.5,
    discountPrice: 1.3,
    discountPercentage: "13%",
    description: "Beetroot Red Bunch, refreshing and healthy. Price per kg.",
    rating: 4.3,
    category: "Vegetables",
    stock: 110,
    size: "1kg",
  },
  {
    id: "7",
    title: "Sweet Onions",
    imageUrl: "https://freepngimg.com/thumb/onion/8-onion-png-image-thumb.png",
    price: 1.0,
    discountPrice: 0.9,
    discountPercentage: "10%",
    description: "Sweet onions, essential for cooking. Price per kg.",
    rating: 4.6,
    category: "Vegetables",
    stock: 140,
    size: "1kg",
  },
  {
    id: "8",
    title: "Colorful Bell Peppers",
    imageUrl: "https://freepngimg.com/thumb/pepper/1-red-pepper-png-image-thumb.png",
    price: 2.2,
    discountPrice: 2.0,
    discountPercentage: "10%",
    description: "Colorful bell peppers, great for stir-fries. Price per kg.",
    rating: 4.5,
    category: "Vegetables",
    stock: 75,
    size: "1kg",
  },
  {
    id: "9",
    title: "Fresh Pumpkin",
    imageUrl: "https://freepngimg.com/thumb/pumpkin/14-2-pumpkin-png-file-thumb.png",
    price: 3.8,
    description: "Fresh pumpkin, perfect for grilling. Price per kg.",
    rating: 4.4,
    category: "Vegetables",
    stock: 60,
    size: "1kg",
  },
  {
    id: "10",
    title: "Versatile Cabbage",
    imageUrl: "https://freepngimg.com/thumb/cabbage/11-cabbage-png-image-thumb.png",
    price: 2.5,
    discountPrice: 2.2,
    discountPercentage: "12%",
    description: "Fresh cabbage, versatile for cooking. Price per kg.",
    rating: 4.3,
    category: "Vegetables",
    stock: 50,
    size: "1kg",
  },


  {
    id: "12",
    title: "Nido Milk Powder",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/NewBookImages-1-1-600x600.png",
    price: 20,
  
    description: "Fresh milk powder, rich in calcium.",
    rating: 4.7,
    category: "Dairy",
    stock: 150,
    size: "1kg",
  },
  {
    id: "13",
    title: "Laughing Cow Cheese Reduced Fat",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2021/09/NewBookImages-2023-10-11T034014.691-600x600.png",
    price: 25.99,
    description: "Mild cheddar cheese, perfect for sandwiches.",
    rating: 4.6,
    category: "Dairy",
    stock: 100,
    size: "128g",
  },
  {
    id: "100",
    title: "Blue Band Gold 200g ",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/08/NewBookImages-2024-04-17T164811.869-600x600.png",
    price: 16.50,
    description: "Creamy butter, perfect for baking.",
    rating: 4.8,
    category: "Dairy",
    stock: 120,
    size: "200g",
  },
  {
    id: "14",
    title: "Goodburry Fruit Yoghurt 0.1% -Strawberry(4pcs) ",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/01/NewBookImages-82-600x600.png",
    price: 32.99,
    description: "Creamy butter, perfect for baking.",
    rating: 4.8,
    category: "Dairy",
    stock: 120,
    size: "125g",
  },
  {
    id: "15",
    title: "Pascual Thick Creamy Yogurt Strawberry ",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/08/5-3-600x600.png",
    price: 20.45,
    description: "Plain yogurt, smooth and creamy.",
    rating: 4.5,
    category: "Dairy",
    stock: 110,
    size: "(4 pcs) 125g",
  },
  {
    id: "16",
    title: "Pascual Flavored Yogurt Pineapple ",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/08/12-3-600x600.png",
    price: 20.45,
    description: "Thick and creamy Greek yogurt.",
    rating: 4.5,
    category: "Dairy",
    stock: 110,
    size: "(4pcs) 125g",
  },
  {
    id: "166",
    title: "Pascual Greek Yogurt Strawberry",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/08/0012917_pascual-greek-yogurt-strawberry-500g_510.png",
    price: 20.45,
    description: "Thick and creamy Greek yogurt.",
    rating: 4.5,
    category: "Dairy",
    stock: 110,
    size: "(4pcs) 125g",
  },
  {
    id: "17",
    title: "Goodburry Fruit Yogurt - Strawberry (4pcs)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/01/NewBookImages-83-300x300.png",
    price: 132.99,
    description: "Delicious strawberry-flavored yogurt.",
    rating: 4.5,
    category: "Dairy",
    stock: 110,
    size: "4x125g",
  },
  {
    id: "18",
    title: "The Laughing Cow Cheese (120g)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2021/06/NewBookImages-44-300x300.png",
    price: 2.5,
    discountPrice: 2.2,
    discountPercentage: "12%",
    description: "Rich and creamy cheese spread. Perfect for snacks.",
    rating: 4.7,
    category: "Dairy",
    stock: 80,
    size: "120g",
  },
  {
    id: "19",
    title: "Peak UHT Full Cream Milk (1L)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/03/NewBookImages-41-300x300.png",
    price: 3.0,
    discountPrice: 2.7,
    discountPercentage: "10%",
    description: "Delicious UHT full cream milk.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "1L",
  },
  {
    id: "21",
    title: "Alpro Soya Drink Vanilla",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2021/09/NewBookImages-2024-01-03T110606.929-300x300.png",
    price: 3.0,
    discountPrice: 2.7,
    discountPercentage: "10%",
    description: "Delicious vanilla-flavored soya drink.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "1L",
  },
  {
    id: "22",
    title: "Alpro Almond Organic",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/01/NewBookImages-2024-01-03T110028.735-300x300.png",
    price: 3.0,
    discountPrice: 2.7,
    discountPercentage: "10%",
    description: "Organic almond milk with no added sugar.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "1L",
  },
  {
    id: "23",
    title: "President Whole UHT Milk",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/03/NewBookImages-48-1-300x300.png",
    price: 3.0,
    discountPrice: 2.7,
    discountPercentage: "10%",
    description: "Rich and creamy UHT milk.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "1L",
  },
  {
    id: "24",
    title: "EcoMil Almond Milk Organic Calcium",
    imageUrl: "https://cdnx.jumpseller.com/villarrica-gourmet-store/image/57614710/resize/610/610?1732640732",
    price: 3.0,
    discountPrice: 2.7,
    discountPercentage: "10%",
    description: "Organic almond milk, gluten-free, no sugar.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "1L",
  },
  {
    id: "25",
    title: "Jaouda Whole UHT Milk",
    imageUrl: "https://mini-gros.com/549-large_default/lait-uht-entier-500ml-jaouda.jpg",
    price: 1.5,
    discountPrice: 1.35,
    discountPercentage: "10%",
    description: "Fresh and creamy UHT milk.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "500ml",
  },
  {
    id: "26",
    title: "Jibal Whole UHT Milk",
    imageUrl: "http://www.jibal.ma/wp-content/uploads/2018/10/uht-milk-entier-05l.png",
    price: 1.5,
    discountPrice: 1.35,
    discountPercentage: "10%",
    description: "Pure and nutritious UHT milk.",
    rating: 4.8,
    category: "Dairy",
    stock: 50,
    size: "500ml",
  },
  {
    id: "28",
    title: "Bonita Cream Cracker 80g",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/08/10-5-300x300.png",
    price: 49.99,
    description: "Nut-filled energy bars, perfect for snacks.",
    rating: 4.6,
    category: "Snacks",
    stock: 150,
    size: "80g",
  },
  {
    id: "29",
    title: "Borggreve Hazelnut Shortbread Biscuit",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/4-1-300x300.png",
    price: 49.99,
    description: "Energy bars loaded with dried fruits.",
    rating: 4.5,
    category: "Snacks",
    stock: 120,
    size: "200g",
  },
  {
    id: "30",
    title: "Boss Baker Cake Chocolate Chips (10 pieces)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/01/1-20-300x300.png",
    price: 50.55,
    description: "Rich caramel candy, individually wrapped.",
    rating: 4.7,
    category: "Snacks",
    stock: 200,
    size: "10 pieces",
  },
  {
    id: "36",
    title: "Boss Baker Fruit Cake",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/01/7-18-600x600.png",
    price: 38.55,
    description: "Bold Texas BBQ-flavored chips.",
    rating: 4.6,
    category: "Snacks",
    stock: 170,
    size: "20g",
  },
  {
    id: "31",
    title: "Alpenliebe Strawberry Milky Candy",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/08/NewBookImages-2-300x300.png",
    price: 50.55,
    description: "Delicious strawberry-flavored milky candies.",
    rating: 4.8,
    category: "Snacks",
    stock: 180,
    size: "3g (50pcs)",
  },
  {
    id: "34",
    title: "Alpenliebe Cappuccino Milky Candy",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/08/NewBookImages-1-300x300.png",
    price: 50.55,
    description: "Rich cappuccino-flavored milky candies.",
    rating: 4.6,
    category: "Snacks",
    stock: 150,
    size: "3g (50pcs)",
  },
  {
    id: "35",
    title: "Balona Tea Time Onion Biscuits",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/07/NewBookImages-4-300x300.png",
    price: 26.99,
    description: "Crispy onion-flavored biscuits.",
    rating: 4.4,
    category: "Snacks",
    stock: 160,
    size: "15g (10pcs)",
  },

  {
    id: "37",
    title: "Boss Baker Chocolate Cake 20g",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/11/NewBookImages-16-300x300.png",
    price: 7.45,
    description: "Maxi-sized chocolate treat.",
    rating: 4.7,
    category: "Snacks",
    stock: 130,
    size: "20g (10pcs)",
  },
  {
    id: "38",
    title: "Borggreve Chocolate Shortbread Biscuit",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/09/6-2-300x300.png",
    price: 41.45,
    description: "Rich chocolate-filled shortbread biscuits.",
    rating: 4.5,
    category: "Snacks",
    stock: 140,
    size: "200g",
  },
  {
    id: "39",
    title: "Borggreve Coconuts Shortbread",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/09/5-2-300x300.png",
    price: 41.99,
    description: "Coconut-flavored shortbread biscuits.",
    rating: 4.6,
    category: "Snacks",
    stock: 170,
    size: "200g",
  },
  {
    id: "40",
    title: "Pringles Salt & Vinegar Chips",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/1-1-300x300.png",
    price: 38.55,
    description: "Tangy salt & vinegar-flavored chips.",
    rating: 4.6,
    category: "Snacks",
    stock: 170,
    size: "165g",
  },
  {
    id: "41",
    title: "Pringles Chips Cheddar Cheese",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2021/06/309-1-300x300.png",
    price: 1.8,
    discountPrice: 1.5,
    discountPercentage: "17%",
    description: "Crispy cheddar cheese-flavored chips.",
    rating: 4.7,
    category: "Snacks",
    stock: 150,
    size: "165g",
  },
  {
    id: "42",
    title: "Doritos Sweet Chilli Chips",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/04/15-4-300x300.png",
    price: 35.99,
    description: "Sweet and spicy chili-flavored tortilla chips.",
    rating: 4.7,
    category: "Snacks",
    stock: 150,
    size: "145g",
  },
  {
    id: "43",
    title: "Doritos Sour Cream & Chilli Chips",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/04/14-4-300x300.png",
    price: 35.99,
    description: "Tangy sour cream and chili-flavored tortilla chips.",
    rating: 4.7,
    category: "Snacks",
    stock: 150,
    size: "145g",
  },
  {
    id: "44",
    title: "Doritos Cheese Supreme Chips",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/04/13-3-300x300.png",
    price: 6.50,
    description: "Rich cheese-flavored tortilla chips.",
    rating: 4.7,
    category: "Snacks",
    stock: 150,
    size: "30g",
  },
  {
    id: "45",
    title: "SIR Laundry Softener",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/14-4-300x300.png",
    price: 29.99,
    description: "Softens clothes with a refreshing fragrance.",
    rating: 4.7,
    category: "Laundry",
    stock: 100,
    size: "1L",
  },
  {
    id: "46",
    title: "SIR Laundry Softener",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/SIR-Softener-Fresh-Flower-1L-removebg-preview-1.png",
    price: 28.99,
    description: "Softens fabrics and removes tough odors.",
    rating: 4.6,
    category: "Laundry",
    stock: 120,
    size: "3L",
  },
  {
    id: "47",
    title: "SIR Laundry Softener",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/13-4-300x300.png",
    price: 28.99,
    description: "Provides softness and long-lasting freshness.",
    rating: 4.8,
    category: "Laundry",
    stock: 150,
    size: "3L",
  },
  {
    id: "48",
    title: "Sunlight Washing Powder Yellow",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2021/04/2-4-300x300.png",
    price: 18.99,
    description: "Powerful stain remover with a fresh scent.",
    rating: 4.7,
    category: "Laundry",
    stock: 100,
    size: "1kg",
  },
  {
    id: "49",
    title: "Sunlight Eureka Pink",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2021/04/10-2-300x300.png",
    price: 5.99,
    description: "Compact washing powder for tough stains.",
    rating: 4.6,
    category: "Laundry",
    stock: 130,
    size: "180g",
  },
  {
    id: "50",
    title: "Neat All Purpose Cleaner (Floral)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/07/46-300x300.png",
    price: 46.50,
    description: "Effective cleaner with a floral scent.",
    rating: 4.5,
    category: "Laundry",
    stock: 90,
    size: "2L",
  },
  {
    id: "51",
    title: "SIR Liquid Dishwashing Machine Cleaner",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/21-2-300x300.png",
    price: 37.99,
    description: "Efficient cleaning for dishwashers, removes grease and buildup.",
    rating: 4.6,
    category: "Cleaning Supplies",
    stock: 50,
    size: "250ml",
  },
  {
    id: "52",
    title: "SIR Perfumed Surface Cleaner (Honeysuckle)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/17-2-300x300.png",
    price: 26.99,
    description: "Leaves surfaces sparkling clean with a honeysuckle scent.",
    rating: 4.4,
    category: "Cleaning Supplies",
    stock: 140,
    size: "1L",
  },
  {
    id: "53",
    title: "La Salud WC Cleaner Pine Scent",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/06/7-300x300.png",
    price: 41.99,
    description: "Powerful toilet cleaner with a fresh pine scent.",
    rating: 4.5,
    category: "Cleaning Supplies",
    stock: 75,
    size: "1L",
  },
  {
    id: "54",
    title: "Clean & Fresh Fabric Conditioner (Summer Haze)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/09/cklea-300x300.png",
    price: 22.50,
    description: "Softens fabrics and leaves a summer haze fragrance.",
    rating: 4.6,
    category: "Laundry",
    stock: 100,
    size: "1L",
  },
  {
    id: "55",
    title: "Bread",
    imageUrl: "https://freepngimg.com/download/temp_png/25-bread-png-image_400x400.png",
    price: 2.5,
    discountPrice: 2.2,
    discountPercentage: "12%",
    description: "Freshly baked white bread, soft and fluffy.",
    rating: 4.7,
    category: "Bakery",
    stock: 150,
    size: "1 loaf",
  },
  {
    id: "56",
    title: "Croissants",
    imageUrl: "https://freepngimg.com/download/temp_png/29016-1-croissant-transparent-image_400x400.png",
    price: 3.0,
    discountPrice: 2.5,
    discountPercentage: "17%",
    description: "Flaky, buttery croissants perfect for breakfast.",
    rating: 4.8,
    category: "Bakery",
    stock: 120,
    size: "1 piece",
  },
  {
    id: "57",
    title: "Donuts",
    imageUrl: "https://freepngimg.com/download/temp_png/55080-6-donut-picture-download-hq-png_400x400.png",
    price: 2.8,
    discountPrice: 2.5,
    discountPercentage: "11%",
    description: "Deliciously moist donuts in various flavors.",
    rating: 4.7,
    category: "Bakery",
    stock: 100,
    size: "1 piece",
  },
  {
    id: "58",
    title: "Brown Bread",
    imageUrl: "https://freepngimg.com/thumb/bread/94-bread-png-image-thumb.png",
    price: 3.0,
    discountPrice: 2.7,
    discountPercentage: "10%",
    description: "Nutritious whole-grain bread, rich in fiber.",
    rating: 4.6,
    category: "Bakery",
    stock: 140,
    size: "1 loaf",
  },
  {
    id: "59",
    title: "Bagels",
    imageUrl: "https://freepngimg.com/download/temp_png/170603-bagel-sweet-free-hq-image_400x400.png",
    price: 1.8,
    discountPrice: 1.5,
    discountPercentage: "17%",
    description: "Soft and chewy bagels, perfect with cream cheese.",
    rating: 4.5,
    category: "Bakery",
    stock: 130,
    size: "1 piece",
  },
  {
    id: "60",
    title: "Cinnamon Rolls",
    imageUrl: "https://freepngimg.com/download/temp_png/22-bread-png-image_400x400.png",
    price: 3.5,
    discountPrice: 3.2,
    discountPercentage: "8%",
    description: "Warm cinnamon rolls with a sweet glaze.",
    rating: 4.9,
    category: "Bakery",
    stock: 90,
    size: "1 piece",
  },
  
  {
    id: "79",
    title: "Cereal Baguette",
    imageUrl: "https://freepngimg.com/download/temp_png/25-bread-png-image_400x400.png",
    price: 2.5,
    discountPrice: 2.2,
    discountPercentage: "12%",
    description: "Crunchy baguette made with wholesome cereals.",
    rating: 4.6,
    category: "Bakery",
    stock: 80,
    size: "1 piece",
  },
  {
    id: "71",
    title: "Poppy Seed Baguette",
    imageUrl: "https://freepngimg.com/download/temp_png/130692-rustic-baguette-bread-free-download-png-hq_400x400.png",
    price: 4.0,
    discountPrice: 3.5,
    discountPercentage: "13%",
    description: "Baguette topped with aromatic poppy seeds.",
    rating: 4.7,
    category: "Bakery",
    stock: 110,
    size: "1 piece",
  },
  {
    id: "72",
    title: "Bel Cola 350ml (16 pcs)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/02/NewBookImages-21-300x300.png",
    price: 4.0,
    description: "Refreshing cola, ideal for gatherings.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "350ml (16 pcs)",
  },
  {
    id: "73",
    title: "Bel Squeeze Grape Drink 350ml (16 pcs)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/02/NewBookImages-2024-02-22T130653.690-300x300.png",
    price: 4.0,
    description: "Delicious grape-flavored beverage for any occasion.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "350ml (16 pcs)",
  },
  {
    id: "74",
    title: "Bel Squeeze Orange Drink 350ml (16 pcs)",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2024/02/NewBookImages-15-300x300.png",
    price: 4.0,
    description: "Zesty orange drink, perfect for refreshment.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "350ml (16 pcs)",
  },
  {
    id: "75",
    title: "Beta Malt 330ml",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2022/01/NewBookImages-32-1-300x300.png",
    price: 9.99,
    description: "Rich malt drink, great for energy.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "330ml",
  },
  {
    id: "76",
    title: "Ceres 100% Red Grape Juice 1L",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/04/NewBookImages-2024-08-30T141331.164-300x300.png",
    price: 20.99,
    description: "Pure red grape juice with no added sugar.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "1L",
  },
  {
    id: "77",
    title: "Ceres 100% Whispers Of Summer Juice 200ml",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/04/NewBookImages-2024-08-30T143038.200-300x300.png",
    price: 8.99,
    description: "Refreshing summer-inspired fruit juice.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "200ml",
  },
  {
    id: "78",
    title: "Ceres 100% Secret Valley Juice 1L",
    imageUrl: "https://www.chopboxonline.com/wp-content/uploads/2023/09/23-4-300x300.png",
    price: 20.99,
    description: "Tropical fruit juice blend with vibrant flavors.",
    rating: 4.7,
    category: "Beverages",
    stock: 110,
    size: "1L",
  },
  
  
];

export const Fruits= data.filter(el=> el.category==="Fruits")
export const Vegetables= data.filter(el=> el.category==="Vegetables")
export const Dairy= data.filter(el=> el.category==="Dairy")
export const Bakery= data.filter(el=> el.category==="Bakery")
export const Beverages= data.filter(el=> el.category==="Beverages")
export const Snacks= data.filter(el=> el.category==="Snacks")
export const Laundry= data.filter(el=> el.category==="Laundry")
export const discounts=data.filter(el=> el.discountPrice)
//.sort(() => Math.random() - 0.5);